apiVersion: v1
kind: Service
metadata:
  name: mkdocs-service
spec:
  selector:
    app: mkdocs
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort  # LoadBalancer   ClusterIP
