site_name: Gerard's Documentation
repo_name: gerard.io
site_url: https://sosotechnologies.github.io/soso_technologies_macaz_doc.io/
repo_url: https://github.com/sosotechnologies/soso_technologies_macaz_doc.io
edit_uri: https://github.com/sosotechnologies/soso_technologies_macaz_doc.io/repo/blob/main/docs/index.md
theme:
  name: readthedocs
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra_css:
- assets/stylesheets/extra.css
extra_javascript:
- assets/javascripts/extra.js
extra:
  social:
  - type: github
    link: https://github.com/sosotechnologies/
  - type: medium
    link: https://medium.com/@sosotechglobal/

markdown_extensions:
- markdown.extensions.admonition
nav:
 - Home: 
   - About Us: index.md

 - Weekly Lectures: 
   - CICD: weekly/CICD/cicd.md
   - PYTHON: weekly/pytho/pyhton-east.md
